-- MySQL Script generated by MySQL Workbench
-- Thu May  8 13:42:12 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Customers` (
  `idCustomers` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NULL,
  `LastName` VARCHAR(45) NULL,
  `PhoneNumber` VARCHAR(20) NULL,
  `Email` VARCHAR(100) NULL,
  `Address` VARCHAR(100) NULL,
  PRIMARY KEY (`idCustomers`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Basket`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Basket` (
  `idBasket` INT NOT NULL AUTO_INCREMENT,
  `CreationDate` DATE NULL,
  `Status` VARCHAR(45) NULL,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idBasket`),
  INDEX `fk_Basket_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Basket_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bill`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Bill` (
  `idBill` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NULL,
  `TotalAmount` DECIMAL(2) NULL,
  `PaymentMethod` VARCHAR(45) NOT NULL,
  `Customers_idCustomers` INT NOT NULL,
  PRIMARY KEY (`idBill`),
  INDEX `fk_Bill_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  CONSTRAINT `fk_Bill_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departement` (
  `idDepartement` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Description` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idDepartement`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL AUTO_INCREMENT,
  `NameProduct` VARCHAR(45) NOT NULL,
  `DescriptionProduct` VARCHAR(100) NOT NULL,
  `Price` DECIMAL(10,2) NOT NULL,
  `ExpirationDate` DATE NOT NULL,
  `StockQuantity` INT NOT NULL,
  `Departement_idDepartement` INT NOT NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `fk_Product_Departement1_idx` (`Departement_idDepartement` ASC) VISIBLE,
  CONSTRAINT `fk_Product_Departement1`
    FOREIGN KEY (`Departement_idDepartement`)
    REFERENCES `mydb`.`Departement` (`idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BillLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BillLine` (
  `idBillLine` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `SubTotal` DECIMAL(10,2) NULL,
  `Bill_idBill` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idBillLine`),
  INDEX `fk_BillLine_Bill1_idx` (`Bill_idBill` ASC) VISIBLE,
  INDEX `fk_BillLine_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_BillLine_Bill1`
    FOREIGN KEY (`Bill_idBill`)
    REFERENCES `mydb`.`Bill` (`idBill`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BillLine_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Employee` (
  `idEmployee` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Position` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Departement_idDepartement` INT NOT NULL,
  PRIMARY KEY (`idEmployee`),
  INDEX `fk_Employee_Departement1_idx` (`Departement_idDepartement` ASC) VISIBLE,
  CONSTRAINT `fk_Employee_Departement1`
    FOREIGN KEY (`Departement_idDepartement`)
    REFERENCES `mydb`.`Departement` (`idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sales` (
  `idSales` INT NOT NULL AUTO_INCREMENT,
  `Date` DATE NOT NULL,
  `QuantitySold` INT NULL,
  `TotalAmount` INT NULL,
  PRIMARY KEY (`idSales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Promotion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Promotion` (
  `idPromotion` INT NOT NULL AUTO_INCREMENT,
  `DiscountRate` INT NULL,
  PRIMARY KEY (`idPromotion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stock`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stock` (
  `idStock` INT NOT NULL AUTO_INCREMENT,
  `QuantityAvailable` INT NULL,
  `Location` VARCHAR(45) NULL,
  `LastRestockDate` DATE NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idStock`),
  INDEX `fk_Stock_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Stock_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BasketLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`BasketLine` (
  `idBasketLine` INT NOT NULL AUTO_INCREMENT,
  `Quantity` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `Basket_idBasket` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idBasketLine`),
  INDEX `fk_BasketLine_Basket1_idx` (`Basket_idBasket` ASC) VISIBLE,
  INDEX `fk_BasketLine_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_BasketLine_Basket1`
    FOREIGN KEY (`Basket_idBasket`)
    REFERENCES `mydb`.`Basket` (`idBasket`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_BasketLine_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supplier` (
  `idSupplier` INT NOT NULL AUTO_INCREMENT,
  `CompagnyName` VARCHAR(45) NOT NULL,
  `ContactName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(20) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `Address` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`idSupplier`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PurchaseOrderSupplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PurchaseOrderSupplier` (
  `idPurchaseOrderSupplier` INT NOT NULL AUTO_INCREMENT,
  `QuantityOrdered` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `OrderDate` DATE NULL,
  `Supplier_idSupplier` INT NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`idPurchaseOrderSupplier`),
  INDEX `fk_PurchaseOrderSupplier_Supplier1_idx` (`Supplier_idSupplier` ASC) VISIBLE,
  INDEX `fk_PurchaseOrderSupplier_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_PurchaseOrderSupplier_Supplier1`
    FOREIGN KEY (`Supplier_idSupplier`)
    REFERENCES `mydb`.`Supplier` (`idSupplier`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PurchaseOrderSupplier_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PromotionProduct`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PromotionProduct` (
  `Promotion_idPromotion` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`Promotion_idPromotion`),
  INDEX `fk_Promotion_has_Product_Promotion_idx` (`Promotion_idPromotion` ASC) VISIBLE,
  INDEX `fk_PromotionProduct_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Promotion_has_Product_Promotion`
    FOREIGN KEY (`Promotion_idPromotion`)
    REFERENCES `mydb`.`Promotion` (`idPromotion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PromotionProduct_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SaleLine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SaleLine` (
  `Sales_idSales` INT NOT NULL,
  `Quantity` INT NULL,
  `UnitPrice` DECIMAL(10,2) NULL,
  `Subtotal` DECIMAL(10,2) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`Sales_idSales`),
  INDEX `fk_Product_has_Sales_Sales1_idx` (`Sales_idSales` ASC) VISIBLE,
  INDEX `fk_SaleLine_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Product_has_Sales_Sales1`
    FOREIGN KEY (`Sales_idSales`)
    REFERENCES `mydb`.`Sales` (`idSales`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SaleLine_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductRating`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductRating` (
  `Customers_idCustomers` INT NOT NULL,
  `RatingID` INT NOT NULL,
  `RatingValue` INT NULL,
  `RatingDate` DATE NULL,
  `Comment` VARCHAR(100) NULL,
  `Product_idProduct` INT NOT NULL,
  PRIMARY KEY (`Customers_idCustomers`, `RatingID`, `Product_idProduct`),
  INDEX `fk_Customers_has_Product_Customers1_idx` (`Customers_idCustomers` ASC) VISIBLE,
  INDEX `fk_ProductRating_Product1_idx` (`Product_idProduct` ASC) VISIBLE,
  CONSTRAINT `fk_Customers_has_Product_Customers1`
    FOREIGN KEY (`Customers_idCustomers`)
    REFERENCES `mydb`.`Customers` (`idCustomers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ProductRating_Product1`
    FOREIGN KEY (`Product_idProduct`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
